### ISSUE TITLE
Loss of Heading Text from Bulleted list

### ISSUE THREAD

**Issue by VenkatsQuest** [mwilliamson/python-mammoth#120]
If you're reporting a bug or requesting a feature, please include:
![image](https://user-images.githubusercontent.com/19513440/155337988-6b6986ec-38c7-4cc6-9fc4-0bb689bd06cd.png)

It's returning the following output

`<ul><li><ul><li><ol><li><a id="OLE_LINK4"></a><a id="OLE_LINK3"></a><br /></li></ol></li></ul></li></ul><h2>Amazing Text</h2><p>Amazing text in the paragraph here</p><ul><li><ul><li><ol><li>Lets see how it goes</li><li>How this goes second</li><li>Sorry disappointed here</li></ol></li></ul></li></ul>`

* the HTML output that you'd expect
**as you can see , it's missing REQ1.1.1 , REQ1.1.2 , REQ1.1.3 from the converted text**

If you're reporting a bug, it's also useful to know what platform you're
running on, including:

* 3.9
* Windows 10

**Comment by mwilliamson** [comment]
Could you provide the original document? There's not much I can do without it.

**Comment by VenkatsQuest** [comment]
Here goes it is
[Test.docx](https://github.com/mwilliamson/python-mammoth/files/8132449/Test.docx)

**Comment by VenkatsQuest** [comment]
@mwilliamson  any help / suggestion on this issue ?

**Comment by mwilliamson** [comment]
I'll take a look when I get a chance. I'd ask that you don't continue to ping me here or on Twitter: doing so won't make me look any faster.

**Comment by VenkatsQuest** [comment]
Any Suggestions ?

**Comment by mwilliamson** [comment]
It looks like the text for each item is set in the `w:lvl` element:

```
<w:lvlText w:val="REQ %1.%2.%3"/>
```

Mammoth maps lists in the original document to lists in HTML. Since it seems like you want to have the actual text for the numbering explicitly in the output (rather than set by the HTML lists), your best bet is probably to map those items to a specific CSS class, and then run a post-processor to insert any explicit text/numbering you want.
