### ISSUE TITLE
Keeping table in DOCX while converting to HTML

### ISSUE THREAD

**Issue by phantom153** [mwilliamson/python-mammoth#136]
I have a DOCX file with a table (actually a single-cell table used mainly to mark a box around the text).
Is there a way to create the HTML with this table/box?

**Comment by mwilliamson** [comment]
Could you post a minimal example document, the HTML you're expecting to get, and the HTML you're actually getting?

**Comment by phantom153** [comment]
See attached.
BTW - Re:  #135 - in this example for some reason it did keep the font sizes. In other it didn't....
[NocturnoENG_ Access.zip](https://github.com/mwilliamson/python-mammoth/files/11727983/NocturnoENG_.Access.zip)

**Comment by mwilliamson** [comment]
It looks like a border has been applied to the paragraph rather than being in a table, assuming I'm looking in the right place. The way to handle this with Mammoth would be to apply a paragraph style in Word to the bordered text, and then to use a style mapping to map that Word paragraph style into (for instance) a paragraph with a CSS class that applies a similar border.
