### ISSUE TITLE
Underlines and Header note

### ISSUE THREAD

**Issue by GitBruno** [mwilliamson/python-mammoth#19]
The README states that underlines are supported. But if I add an underline in Word via the underline button it does not transfer over to HTML. Also H1 to H4 is working but H5 and H6 dropping out. Again, the README states this is implemented.

**Comment by mwilliamson** [comment]
Since underline is usually used to indicate a link on the web, Mammoth ignores underlining by default. [You can use a style mapping to describe how underlines should be handled](https://github.com/mwilliamson/python-mammoth#underline).

You can also use a style mapping to control how your headings are mapped. Having said that, if Word has headings down to "Heading 6" by default, then I'll happily add them to the default style map.

**Comment by GitBruno** [comment]
OK cool. Agree with the underlines! For the headings, word goes all the way to header 9 but HTML only supports to H6, so I think it will be nice to add H5 and H6. I'll create a pull request today.

**Comment by mwilliamson** [comment]
Handled by #21.
