### ISSUE TITLE
Finish class LineBreak(Element)

### ISSUE THREAD

**Issue by GitBruno** [mwilliamson/python-mammoth#20]
With option to add class for break type

**Comment by mwilliamson** [comment]
Could you provide a minimal example document and the HTML that you expect to be generated?

**Comment by GitBruno** [comment]
See below:

[PageBreak_Test.zip](https://github.com/mwilliamson/python-mammoth/files/552112/PageBreak_Test.zip)

**Comment by GitBruno** [comment]
Just to clarify. There are two things:

    1: Empty paragraphs `<p/>` should translate to break tag `<br />`
    2: Special break characters (like page-break etc) should translate to break tag with class: `<br class='pageBreak'`

**Comment by mwilliamson** [comment]
> 1: Empty paragraphs `<p/>` should translate to break tag `<br />`  

My feeling is that converting empty paragraphs to break tags would be better performed as a post-processing step after Mammoth has done the conversion, since it should be straightforward to write and avoids adding complexity to Mammoth.

>     2: Special break characters (like page-break etc) should
> translate to break tag with class: `<br class='pageBreak'`  

Sounds reasonable, but not sure when I'll get a chance to look at this. I think the default behaviour for page breaks should stay the same (sans warning). I'd imagine you can change the behaviour using a style mapping.

**Comment by mwilliamson** [comment]
Oh, and to clarify: I think the default behaviour for page breaks
should stay the same (sans warning). I'd imagine you can change the
behaviour using a style mapping.

**Comment by mwilliamson** [comment]
> 1: Empty paragraphs `<p/>` should translate to break tag `<br />`

My feeling is that converting empty paragraphs to break tags would be
better performed as a post-processing step after Mammoth has done the
conversion, since it should be straightforward to write and avoids
adding complexity to Mammoth.

>     2: Special break characters (like page-break etc) should
> translate to break tag with class: `<br class='pageBreak'`

Sounds reasonable, but not sure when I'll get a chance to look at this.

**Comment by GitBruno** [comment]
1: Post processing it is! 

2: It can stay as is but it would be good if we could override it with a style map. I tried to add the style map. But I guess we need to add this to the grammar? If you can give me some guidance where to look or what to do, I would be more then happy to execute.

> Did not understand this style mapping, so ignored it: w[type='page'] => br.pageBreak:fresh

**Comment by mwilliamson** [comment]
There are a few different pieces that need to be changed:

* Changing `mammoth/docx/body_xml.py` to handle different break types (see the `br` function). This will also involve a change to the document AST that Mammoth uses internally so that it can track break types other than line breaks.

* Changing `mammoth/style_reader/document_matcher_reader.py` to read style mappings for breaks (probably something like `br` would do since it matches the XML, and `br` is already familiar as a break thanks to HTML)

* Changing `mammoth/conversion.py` to use the style mappings for breaks when converting breaks.

Each of those modules also has some associated tests, so it should be straightforward to add similar tests.

**Comment by GitBruno** [comment]
Cool, thanks! I'll have a look at it.

**Comment by mwilliamson** [comment]
Some coordination is needed with the Mammoth implementation to make sure they behave the same (and also have a similar implementation). See: https://github.com/mwilliamson/mammoth.js/issues/102

**Comment by GitBruno** [comment]
We need to make sure to keep mammoth semantical. Page Break is a type of <br> not  <hr>. This should be possible with style map.

I havent had time to look at it yet, but it is on my list of things to do!

**Comment by GitBruno** [comment]
Type of break is not horizontal ruler. 

Make sure we can use style map on any type of break.

**Comment by GitBruno** [comment]
On top of that, we could add a general catcher: w[type='anybreak'] => hr:fresh ?

**Comment by mwilliamson** [comment]
I don't think we need to solve everything in one go. Let's just aim for the breaks that people use most frequently first, which is probably line breaks and page breaks (unless there are any more that you need for your use case?)

I'd imagined the style mappings to look something like

```
br[type='line'] => br # Convert line breaks to <br>, which should be the default behaviour anyway
br[type='page'] => hr # Convert page breaks to <hr>
br => hr # Convert all breaks to <hr>
```

**Comment by GitBruno** [comment]
Sounds good. Page break and Section break are the two I need.

**Comment by GitBruno** [comment]
Hey this stopped working in 1.3.3?

    br[type='line'] => br.line
    br[type='column'] => br.column
    br[type='page'] => br.page

**Comment by mwilliamson** [comment]
Nothing around breaks has been (intentionally) changed. Could you provide

* an example document
* how you're using Mammoth
* which version of Mammoth was working previously

**Comment by GitBruno** [comment]
[multiPage_test.docx.zip](https://github.com/mwilliamson/python-mammoth/files/905887/multiPage_test.docx.zip)

    style_map = " br[type='line'] => br.line \n
                   br[type='column'] => br.column \n
                   br[type='page'] => br.page "

    mammoth.convert_to_html(docx_file, style_map=style_map, ignore_empty_paragraphs=False)

Working in version mammoth 1.3.0 under python 2.7 but not under 1.3.3

It seems that style mapping is not working at all anymore in the new version?

**Comment by mwilliamson** [comment]
Seems to be working when I try it out on your example document with a fresh install of Mammoth 1.3.3. Could you provide a complete code snippet?
