### ISSUE TITLE
How to convert text alignment to html

### ISSUE THREAD

**Issue by Mr-ziqiang** [mwilliamson/python-mammoth#22]
I will convert text alignment to html,but not support.

<w:p w:rsidR="006F2D0A" w:rsidRDefault="006F2D0A" w:rsidP="006F2D0A">
<w:pPr>
<w:jc w:val="center"/>
</w:pPr>
<w:r>
<w:t>textAlign</w:t>
</w:r>
</w:p>

**Comment by mwilliamson** [comment]
Mammoth is intended to be used with documents that have been semantically marked up. So, rather than trying to match the formatting exactly, you'd have a paragraph in Word with an appropriate style, which can then be mapped to a corresponding CSS class.

In this case, rather than centring the text, give it a style that will centre the centre, and then map that style to an appropriate CSS class.
