### ISSUE TITLE
Does not retain Heading numbers while generating output HTML

### ISSUE THREAD

**Issue by rushikesh988** [mwilliamson/python-mammoth#56]
Thanks for creating this amazing library. I am trying to convert one basic docx to HTML it seems to be loosing section/heading numbers while doing it .  Is there is something which I am missing , I tried using styles to at least convert headings/sections into H1 . However it also seem to be not working. Is there anyway I can Retain Heading/Section Numbers . 

```

style_map = """
style-name='Heading1' => h1:fresh
style-name='Heading 1' => h1:fresh
style-name='_MTHeading 2' => h1:fresh
style-name='_MTHeading2' => h1:fresh
"""


with open("test2.docx", "rb") as docx_file:
    result = mammoth.convert_to_html(docx_file,style_map=style_map)
    html = result.value 
    messages = result.messages 

f=open('result.html','wb')
f.write(html.encode("utf-8"))
f.close()

```

[test2.docx](https://github.com/mwilliamson/python-mammoth/files/1824611/test2.docx)

**Comment by mwilliamson** [comment]
The style map needs tweaking to work correctly:

```python
style_map = """
p[style-name='Heading1'] => h1:fresh
p[style-name='Heading 1'] => h1:fresh
p[style-name='_MTHeading 2'] => h1:fresh
p[style-name='_MTHeading2'] => h1:fresh
"""
```

As for the numbering: assuming the numbering is part of the style itself, rather than text you've entered directly into the document, there's no way to get Mammoth to automatically add the numbering to the HTML. Your best bet is probably to convert the headings to `h1`, `h2`, etc. as appropriate, and then post-process the resulting HTML to add in the numbering.

**Comment by rushikesh988** [comment]
@mwilliamson Thanks a lot this has solved issue. I will post process for number.
