### ISSUE TITLE
Problems with heading detection after converting

### ISSUE THREAD

**Issue by MichaelGuardian** [mwilliamson/python-mammoth#64]
If the document was created in an older version of word the heading detection does not work properly.

After converting it to avoid comatibility mode the problem persists. The first heading of the document seems to work but all that follow are not recognized.

Also observed that the headings inside word are not collapsable. May be an issue with word itself.

**Comment by mwilliamson** [comment]
Could you provide a minimal example document? Do you get any messages when running the conversion?

If the heading is formatted using a paragraph style, then you should be able to define a style map to handle the conversion. If the heading if formatted using ad-hoc formatting, then Mammoth won't try to copy the exact formatting by design.

**Comment by MichaelGuardian** [comment]
After some testing I came to the conclusion that the bug has nothing to do with mammoth but with how office applications handle compatibility versions.
