### ISSUE TITLE
list or numbered lists not applied when inside another style

### ISSUE THREAD

**Issue by rageshchalil** [mwilliamson/python-mammoth#73]
I have a paragraph with style say "body-content", and there are list and ordered lists in this paragraph style.

The conversions that I am doing.
p[style-name='body-content'] => div.body-content 

For some reason the list and ordered lists are not getting converted, am I missing anything or should I be using another approach?

**Comment by mwilliamson** [comment]
Could you provide a minimal example document? Do you get any messages in the result?

**Comment by rageshchalil** [comment]
[sample.docx](https://github.com/mwilliamson/python-mammoth/files/2805317/sample.docx)
@mwilliamson , attached a sample document, in the document the "body-indication" style has contents which are plain <p> tags as well lists.

My style map is:
p[style-name='body-indication'] => div.body-indication

the list's style do not get converted to <ul><li>....

Can you please advise, if there is anything I am missing?

**Comment by mwilliamson** [comment]
When you try converting the document without the style map, do the
lists appear correctly?

If the elements of the list have the style "body-indication", then
they'll get converted to divs with the class "body-indication" since
that's what you've described in the style map. It depends on what HTML
you want to generate, but assuming you want to wrap the contents in a
single body-indication div, I think you want a style map along the
lines of:

p[style-name='body-indication']:unordered-list(1) => div.body-indication > ul > li:fresh
p[style-name='body-indication'] => div.body-indication > p:fresh

**Comment by GitBruno** [comment]
Note that `body-indication` is a [linked style](http://www.addbalance.com/usersguide/styles.htm#Character). So pending the cleanliness of the data it can be a character style as well). 

    r[style-name='body-indication'] => div.body-indication > p:fresh

@mwilliamson  Either way, `List` and `Table` styles should be kept. As they fall outside the scope of `Paragraph` and `Character` styles.

![screen shot 2019-01-29 at 11 08 37 am](https://user-images.githubusercontent.com/1421477/51874956-25b33680-23b7-11e9-9f84-c1df240dc27a.png)

**Comment by mwilliamson** [comment]
In that case, I think this can be closed. Glad you got it working.
